### ISSUE TITLE
Question regarding a part of the ddpg training process

### ISSUE THREAD

**Issue by vguillet** [Dekki-Aero/DDPG#2]
Good afternoon,
I am struggling to understand what you did here exactly (this is line 124 to 134 of the DDPG script):

        with tf.GradientTape() as tape:
            a = self.actor(states_batch)
            tape.watch(a)
            q = self.critic([states_batch, a])
        dq_da = tape.gradient(q, a)

        with tf.GradientTape() as tape:
            a = self.actor(states_batch)
            theta = self.actor.trainable_variables
        da_dtheta = tape.gradient(a, theta, output_gradients=-dq_da)
        self.actor_opt.apply_gradients(zip(da_dtheta, self.actor.trainable_variables))

Could you explain especially how a = self.actor(states_batch) works? And additionally if you dont mind. I noticed that you didnt compile the actor model, is this on purpose? 

Thank you!

**Comment by Dekki-Aero** [comment]
a = self.actor(states_batch)

>  "a" gives actions(tensor) predicted by actor network.
